/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example: Input: s = "abcd"; t = "abcde"
 *			Output: e
 * Explanation: 'e' is the letter that was added.
 * https://leetcode.com/problems/find-the-difference/
 *
 * Author: Adam Yu Wen
 * Date: October 6, 2016
 */

class Solution {
public:
	char findTheDifference(string s, string t) {
		int index;
		unordered_map<char, int> myMap;
		for (unsigned int i = 0; i < s.size(); i++) {
			myMap[s[i]]++;
		}
		for (unsigned int i = 0; i < t.size(); i++) {
			myMap[t[i]]--;
			if (myMap[t[i]] < 0) {
				index = i;
				break;
			}
		}
		return t[index];
	}
};